language: elixir
elixir:
    - 1.5.3
    - 1.6.6
    - 1.7.4
    - 1.8.2
    - 1.9.1
otp_release:
    - 19.3
    - 20.3
    - 21.3
    - 22.0

matrix:
  exclude:
    - elixir: 1.5.3
      otp_release: 21.3
    - elixir: 1.5.3
      otp_release: 22.0

    - elixir: 1.6.6
      otp_release: 21.3
    - elixir: 1.6.6
      otp_release: 22.0

    - elixir: 1.8.2
      otp_release: 19.3

    - elixir: 1.9.1
      otp_release: 19.3
